export const InitialCountryValue = {
    alpha2Code: '',
    alpha3Code: '',
    altSpellings: [],
    area: 0,
    borders: [],
    callingCodes: [],
    capital: '',
    cioc: '',
    currencies: [],
    demonym: '',
    flag: '',
    gini: 0,
    languages: [],
    latlng: [],
    name: '',
    nativeName: '',
    numericCode: 0,
    population: 0,
    region: '',
    regionalBlocs: [],
    subregion: '',
    timezones: [],
    topLevelDomain: [],
    translations: ''
    };